site_name: Critical Path Method Analysis
theme: material
nav:
  - Home: index.md
  - Problem Statement: problem.md
  - Network Analysis: network-analysis.md
  - Critical Path Calculation: critical-path.md
  - Results and Conclusion: results.md

markdown_extensions:
  - tables
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

docs_dir: docs
use_directory_urls: false

# Additional configuration
extra:
  assets_dir: assets